AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Tag:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
      - Key: cross-account
        Value: !Ref Tag
Outputs:
  AccountId:
    Value: !Ref AWS::AccountId
  BucketName:
    Value: !Ref S3Bucket
