# This workflow integrates ShiftLeft Scan with GitHub actions
# ShiftLeft Scan is a free open-source security tool for modern DevOps teams
# Visit https://slscan.io/en/latest/integrations/github-actions/ for help
name: ShiftLeft Scan

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        output: reports
        type: aws
    - uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports
